import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  scanForForbiddenPatterns,
  PATTERN_SCAN_IMPLEMENTED_IDS,
  PATTERN_SCAN_NO_OP_IDS,
} from '../verify/patternScan.mjs';
import { FORBIDDEN_PATTERNS_BY_PROFILE } from '../build-contract.mjs';

const makeProject = (fileMap) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'envizzle-pattern-scan-'));
  for (const [relPath, content] of Object.entries(fileMap)) {
    const full = path.join(dir, relPath);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf8');
  }
  return dir;
};

const removeProject = (dir) => {
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
};

/**
 * Run one (id, hitFileMap, missFileMap) case through the scanner and assert:
 *  - the hit fixture produces at least one hit for `id`
 *  - the miss fixture produces zero hits for `id`
 *  - the two fixtures' file contents actually differ (test-discipline guard)
 */
function assertHitAndMiss(id, hitFileMap, missFileMap) {
  const relPath = Object.keys(hitFileMap)[0];
  assert.notEqual(
    hitFileMap[relPath],
    missFileMap[relPath],
    `hit and miss fixtures for "${id}" must differ`,
  );

  const hitDir = makeProject(hitFileMap);
  const missDir = makeProject(missFileMap);
  try {
    const hitResults = scanForForbiddenPatterns(hitDir, [{ id, reason: `test reason for ${id}` }]);
    const missResults = scanForForbiddenPatterns(missDir, [{ id, reason: `test reason for ${id}` }]);

    assert.ok(
      hitResults.some((h) => h.id === id),
      `expected at least one "${id}" hit in the positive fixture, got: ${JSON.stringify(hitResults)}`,
    );
    for (const hit of hitResults) {
      assert.equal(hit.id, id);
      assert.equal(typeof hit.file, 'string');
      assert.ok(hit.file.length > 0);
      assert.equal(typeof hit.line, 'number');
      assert.ok(Number.isInteger(hit.line) && hit.line >= 1);
      assert.equal(hit.reason, `test reason for ${id}`);
    }

    assert.deepEqual(
      missResults.filter((h) => h.id === id),
      [],
      `expected zero "${id}" hits in the negative fixture, got: ${JSON.stringify(missResults)}`,
    );
  } finally {
    removeProject(hitDir);
    removeProject(missDir);
  }
}

test('manual-babylon-bindings: flags @group(/@binding( in Babylon-managed shader paths', () => {
  assertHitAndMiss(
    'manual-babylon-bindings',
    { 'src/shaders/terrain.wgsl': '@group(0) @binding(0) var<uniform> params: Params;\nfn vertexMain() {}\n' },
    { 'src/shaders/terrain.wgsl': '// generated by Babylon, no manual bindings here\nfn vertexMain() {}\n' },
  );
});

test('wrong-babylon-shader-language: flags BABYLON.ShaderLanguage.GLSL', () => {
  assertHitAndMiss(
    'wrong-babylon-shader-language',
    { 'src/shaders/material.js': "shaderMaterial.shaderLanguage = BABYLON.ShaderLanguage.GLSL;\n" },
    { 'src/shaders/material.js': "shaderMaterial.shaderLanguage = BABYLON.ShaderLanguage.WGSL;\n" },
  );
});

test('wrong-babylon-shader-store: flags a fallbackGlsl ShaderStore registration', () => {
  assertHitAndMiss(
    'wrong-babylon-shader-store',
    { 'src/shaders/store.js': "BABYLON.Effect.ShadersStore['fallbackGlsl'] = FRAGMENT_SRC;\n" },
    { 'src/shaders/store.js': "BABYLON.ShaderStore.ShadersStoreWGSL['primaryWgsl'] = FRAGMENT_SRC;\n" },
  );
});

test('wgsl-binding-syntax-in-webgl2: flags stray WGSL @group(/@binding( syntax', () => {
  assertHitAndMiss(
    'wgsl-binding-syntax-in-webgl2',
    { 'src/shaders/terrain.glsl': '@group(0) @binding(0) var<uniform> params: Params;\n' },
    { 'src/shaders/terrain.glsl': '#version 300 es\nvoid main() {}\n' },
  );
});

test('wrong-webgl2-shader-language: flags WGSL entry-point syntax in a three-webgl2 project', () => {
  assertHitAndMiss(
    'wrong-webgl2-shader-language',
    { 'src/shaders/terrain.glsl': '@vertex\nfn main() {}\n' },
    { 'src/shaders/terrain.glsl': '#version 300 es\nvoid main() {}\n' },
  );
});

test('webgl1-fallback-context: flags getContext("webgl") instead of "webgl2"', () => {
  assertHitAndMiss(
    'webgl1-fallback-context',
    { 'src/core/engine.js': "const gl = canvas.getContext('webgl');\n" },
    { 'src/core/engine.js': "const gl = canvas.getContext('webgl2');\n" },
  );
});

test('webgl-fallback: flags new BABYLON.Engine( as a lesser-backend fallback', () => {
  assertHitAndMiss(
    'webgl-fallback',
    { 'src/core/engine.js': 'const engine = new BABYLON.Engine(canvas, true);\n' },
    { 'src/core/engine.js': 'const engine = new BABYLON.WebGPUEngine(canvas);\n' },
  );
});

test('cpu-predisplaced-render-mesh: flags CPU height-displacement of render-owned terrain vertices', () => {
  assertHitAndMiss(
    'cpu-predisplaced-render-mesh',
    { 'src/terrain/mesh.js': 'vertex.y = getHeight(x, z);\n' },
    { 'src/terrain/mesh.js': 'vertex.y = 0; // flat at base height, GPU owns elevation\n' },
  );
});

test('cpu-predisplaced-render-mesh: does not flag the allowed CPU mirror in heightfield.js', () => {
  const dir = makeProject({
    'src/terrain/heightfield.js': 'vertex.y = getHeight(x, z); // physics/camera-clearance/foot-planting mirror\n',
  });
  try {
    const results = scanForForbiddenPatterns(dir, [{ id: 'cpu-predisplaced-render-mesh', reason: 'r' }]);
    assert.deepEqual(results, []);
  } finally {
    removeProject(dir);
  }
});

test('placeholder-character: flags a primitive box/sphere/capsule stand-in', () => {
  assertHitAndMiss(
    'placeholder-character',
    { 'src/character/model.js': 'const mesh = new THREE.CapsuleGeometry(0.5, 1.5, 4, 8);\n' },
    { 'src/character/model.js': 'const mesh = buildProceduralSilhouette(archetypeParams);\n' },
  );
});

test('premature-readiness: flags ready:true set without a nearby status==="ready" guard', () => {
  assertHitAndMiss(
    'premature-readiness',
    {
      'src/core/demoDiagnostics.js':
        'function init() {\n  window.__demo.ready = true;\n}\n',
    },
    {
      'src/core/demoDiagnostics.js':
        "function markReady() {\n  if (status === 'ready') {\n    window.__demo.ready = true;\n  }\n}\n",
    },
  );
});

test('suppressed-initialization-failure: flags a src/core catch block that never sets status failed', () => {
  assertHitAndMiss(
    'suppressed-initialization-failure',
    {
      'src/core/engine.js':
        'try {\n  initAdapter();\n} catch (err) {\n  console.log(err);\n}\n',
    },
    {
      'src/core/engine.js':
        "try {\n  initAdapter();\n} catch (err) {\n  status = 'failed';\n  window.__demo.error = err.message;\n}\n",
    },
  );
});

test('render-loop-allocation: flags a `new` allocation inside a render/animate/tick function', () => {
  assertHitAndMiss(
    'render-loop-allocation',
    {
      'src/core/renderLoop.js':
        'function renderFrame() {\n  const tempVec = new Vector3(0, 0, 0);\n  draw(tempVec);\n}\n',
    },
    {
      'src/core/renderLoop.js':
        'function renderFrame() {\n  reuseVec.set(0, 0, 0);\n  draw(reuseVec);\n}\n',
    },
  );
});

test('documented no-op ids never produce hits, even against content that looks violating', () => {
  const dir = makeProject({
    'src/terrain/mesh.js': 'applyHeight(vertex); applyHeight(vertex); // looks "duplicate" but is not a real static signal\n',
    'src/character/model.js': 'setPose("idle"); setPose("locomotion"); // identical-looking poses is a visual-review concern\n',
  });
  try {
    const patterns = PATTERN_SCAN_NO_OP_IDS.map((id) => ({ id, reason: `test reason for ${id}` }));
    const results = scanForForbiddenPatterns(dir, patterns);
    assert.deepEqual(results, [], 'no-op ids must never produce hits');
  } finally {
    removeProject(dir);
  }
});

test('scanForForbiddenPatterns only checks ids present in the passed forbiddenPatterns array', () => {
  const dir = makeProject({
    'src/core/engine.js': 'const engine = new BABYLON.Engine(canvas, true);\n',
  });
  try {
    const results = scanForForbiddenPatterns(dir, [{ id: 'placeholder-character', reason: 'r' }]);
    assert.deepEqual(results, [], 'webgl-fallback content must not be flagged when webgl-fallback is not requested');
  } finally {
    removeProject(dir);
  }
});

test('scanForForbiddenPatterns returns [] when the project has no src/ directory', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'envizzle-pattern-scan-nosrc-'));
  try {
    const results = scanForForbiddenPatterns(dir, [{ id: 'webgl-fallback', reason: 'r' }]);
    assert.deepEqual(results, []);
  } finally {
    removeProject(dir);
  }
});

test('scanForForbiddenPatterns validates its arguments', () => {
  assert.throws(() => scanForForbiddenPatterns('', []), TypeError);
  assert.throws(() => scanForForbiddenPatterns('/tmp/whatever', 'not-an-array'), TypeError);
});

test('PATTERN_SCAN_IMPLEMENTED_IDS exactly matches every id across both forbiddenPatterns profiles', () => {
  const registryIds = new Set();
  for (const list of Object.values(FORBIDDEN_PATTERNS_BY_PROFILE)) {
    for (const entry of list) registryIds.add(entry.id);
  }
  const implementedIds = new Set(PATTERN_SCAN_IMPLEMENTED_IDS);

  const missingFromScanner = [...registryIds].filter((id) => !implementedIds.has(id));
  const extraInScanner = [...implementedIds].filter((id) => !registryIds.has(id));

  assert.deepEqual(
    missingFromScanner,
    [],
    `verify/patternScan.mjs is missing checks (real or documented no-op) for: ${missingFromScanner.join(', ')}`,
  );
  assert.deepEqual(
    extraInScanner,
    [],
    `verify/patternScan.mjs has checks for ids not present in FORBIDDEN_PATTERNS_BY_PROFILE: ${extraInScanner.join(', ')}`,
  );
});

test('every PATTERN_SCAN_NO_OP_IDS entry is also present in PATTERN_SCAN_IMPLEMENTED_IDS', () => {
  const implementedIds = new Set(PATTERN_SCAN_IMPLEMENTED_IDS);
  for (const id of PATTERN_SCAN_NO_OP_IDS) {
    assert.ok(implementedIds.has(id), `no-op id "${id}" must still be listed in PATTERN_SCAN_IMPLEMENTED_IDS`);
  }
});
